name: macos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run setup.sh
        run: |
          export HOMEBREW_BUNDLE_MAS_SKIP=$(brew bundle list --mas | paste -sd " " -)
          ${GITHUB_WORKSPACE}/setup.sh
        env:
          HOMEBREW_BUNDLE_BREW_SKIP: "go mono awscli  golangci-lint jpeg"
          HOMEBREW_BUNDLE_CASK_SKIP: "docker"

      - name: Run deploy
        run: |
          make deploy

      # - name: Load .zshenv
      #   run: |
      #     zsh ~/.zshenv 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi

      # - name: Load .zshrc
      #   run: |
      #     export TERM="xterm-256color"
      #     source ~/.zshrc 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi
