name: macos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Error Check
      # - name: Run brew bundle
      #   run: brew bundle

      - name: Run setup.sh
        run: ${GITHUB_WORKSPACE}/setup.sh

      # - name: Load .bash_profile
      #   run: |
      #     bash ~/.bash_profile 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi
      - name: Load .zshrc
        run: |
          bash ~/.zshrc 2> error.log; cat error.log
          if [ -s error.log ]; then false; fi
