name: macos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade zsh
        run: brew install zsh

      - name: Remove existing symlinks
        run: |
          rm -rf /usr/local/bin/aws
          rm -rf /usr/local/bin/aws_completer
          rm -rf /usr/local/bin/go
          rm -rf /usr/local/bin/gofmt

      - name: Cache brew install step
        uses: actions/cache@v3
        id: cache-setup
        with:
          path: |
            /usr/local/Cellar
            /usr/local/Homebrew
          key: macos-setup-${{ runner.os }}-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            macos-setup-${{ runner.os }}-

      - name: Setup environment variable if cache hit
        if: steps.cache-setup.outputs.cache-hit == 'true'
        run: echo "SKIP_BREW_BUNDLE=true" >> $GITHUB_ENV

      - name: Run setup.sh
        run: |
          export HOMEBREW_BUNDLE_MAS_SKIP=$(brew bundle list --mas | paste -sd " " -)
          ${GITHUB_WORKSPACE}/setup.sh
        env:
          HOMEBREW_BUNDLE_BREW_SKIP: "go mono"
          HOMEBREW_BUNDLE_CASK_SKIP: "docker"

      # - name: Load .zshenv
      #   run: |
      #     zsh ~/.zshenv 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi

      # - name: Load .zshrc
      #   run: |
      #     export TERM="xterm-256color"
      #     source ~/.zshrc 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi
